### ISSUE TITLE
promise.get declaration

### ISSUE THREAD

**Issue by demurgos** [typed-typings/npm-bluebird#1]
Hi,
I would like to know what is the problem with the declaration of [.get](http://bluebirdjs.com/docs/api/get.html).

This is the related part:

``` ts
    /**
     * This is a convenience method for doing:
     *
     * <code>
     * promise.then(function(obj){
    *     return obj[propertyName];
    * });
     * </code>
     */
    // TODO find way to fix get()
    // get<U>(propertyName: string): Promise<U>;
```

Isn't it possible to just type it as `get<U>(key: string | number): Promise<U>;` ?

**Comment by unional** [comment]
Looks like it is possible. The typings was copied from DT, so I would expect they are a bit out of date and not complete.
