### ISSUE TITLE
Bluebird.resolve

### ISSUE THREAD

**Issue by demurgos** [typed-typings/npm-bluebird#12]
Hi,
I encountered an error when I wanted to use `.resolve` to nomalize a value  that could either be a Promise or already resolved. The compiler did not let me do that:

``` typescript
type EventualPromise<T> = T | Bluebird.Thenable<T>;

let eventualStringPromise: EventualPromise<string>;

Bluebird.resolve(eventualPromise)
  .then((resolved: string) => {
    console.log(resolved);
  });
```

This fails because `string | Bluebird.Thenable<string>` is not assignable to `string`.

Here are the related definitions:

``` typescript
// currently:
static resolve(): Bluebird<void>;
static resolve<R>(value: Bluebird.Thenable<R>): Bluebird<R>;
static resolve<R>(value: R): Bluebird<R>;

// Proposed:
static resolve(): Bluebird<void>;
static resolve<R>(value: R | Bluebird.Thenable<R>): Bluebird<R>;
```

**Comment by louy** [comment]
This is why I always prefer having union types over having function overloads.

**Comment by demurgos** [comment]
You're right, in fact it's even easier to read with unions.

``` typescript
static resolve(): Bluebird<void>;
static resolve<R>(value: R | Bluebird.Thenable<R>): Bluebird<R>;
```
