### ISSUE TITLE
.catch definition does not support all predicate types

### ISSUE THREAD

**Issue by robscotts4rb** [typed-typings/npm-bluebird#22]
It is currently valid to define `.catch` using a shorthand predicate. The current definition only supports function predicates. 

Code snippet of a valid `.catch`

```
.catch({code: 'ENOENT'}, function(e) {
    console.log("file not found: " + e.path);
});
```

**Comment by unional** [comment]
Interesting. I never know about that signature. 

Would you be interested in filing a PR?

**Comment by robscotts4rb** [comment]
Pull request added #23

**Comment by unional** [comment]
Thanks again.
