### ISSUE TITLE
Cancellation related type information is missing

### ISSUE THREAD

**Issue by Stubb0rn** [typed-typings/npm-bluebird#25]
Based on Bluebird's [cancellation reference](http://bluebirdjs.com/docs/api/cancellation.html) callback passed to `Promise` constructor should accept optional `onCancel` hook and `Promise` instances should have [cancel](http://bluebirdjs.com/docs/api/cancel.html) method. There is also inspection method [isCancelled](http://bluebirdjs.com/docs/api/iscancelled.html) for checking if promise has been cancelled.

**Comment by unional** [comment]
Fixed by #26
