### ISSUE TITLE
Not assignable to Promise

### ISSUE THREAD

**Issue by felixfbecker** [typed-typings/npm-bluebird#34]
```
[ts] Type 'Bluebird<Model[]>' is not assignable to type 'Promise<User[]>'.
       Types of property 'then' are incompatible.
         Type '{ <U1, U2>(onFulfill: (value: Model[]) => U1 | Thenable<U1>, onReject: (error: any) => U2 | Thena...' is not assignable to type '{ <TResult1, TResult2>(onfulfilled: (value: User[]) => TResult1 | PromiseLike<TResult1>, onreject...'.
           Type 'Bluebird<any>' is not assignable to type 'Promise<any>'.
             Property '[Symbol.toStringTag]' is missing in type 'Bluebird<any>'.
```
This prevents Sequelize users from writing methods with a `Promise` return type and returning a bluebird promise.

types/npm-sequelize#78

**Comment by blakeembrey** [comment]
I think this is reasonable, to be honest, especially if it matches the actual code (E.g. no symbols in Bluebird). What people should be using is `PromiseLike` for input arguments so they can accept anything that looks like a promise and the return types remain correct.

**Comment by felixfbecker** [comment]
I agree. A user can type as `PromiseLike` or the actual `Bluebird` promise.

**Comment by rokoroku** [comment]
I forgot to mention it: 
The remain problem is Typescript doesn't allow `PromiseLike` return type for async functions.
```
[ts] The return type of an async function or method must be the global Promise<T> type.
```

**Comment by unional** [comment]
Relevant topic: https://github.com/Microsoft/TypeScript/issues/5911

**Comment by unional** [comment]
The most relevant comment: https://github.com/Microsoft/TypeScript/issues/5911#issuecomment-162041627
https://github.com/Microsoft/TypeScript/issues/5911#issuecomment-162110385
https://github.com/Microsoft/TypeScript/issues/5911#issuecomment-163078622
https://github.com/Microsoft/TypeScript/pull/6631

**Comment by blakeembrey** [comment]
@rokoroku That's correct and should be unrelated. Use the global `Promise` and not bluebird for the return type of an async function (it'll always be converted at runtime to the global instance).
