### ISSUE TITLE
Lost .get and .join during merge

### ISSUE THREAD

**Issue by demurgos** [typed-typings/npm-bluebird#5]
Hi,
I just noticed that the fix to .get and .join that I made a few weeks ago were lost.
Here is this repo's history: ![Image](http://i.imgur.com/19jwmU5.png)

The loss occurred during the highlighted merge, but it's a bit strange: the other projects did not have the same origin. Is it possible to revert it quickly ? (I'll submit a pull request but maybe there is a better way to do it).

**Comment by demurgos** [comment]
I think that it's better to accept the PR than rollback the previous version of the definition:
The name of the promises changed to `Bluebird` (instead of `Promise`) and I marked the arguments of the `.join` handler as optional.

**Comment by louy** [comment]
The name `Promise` causes conflicts with `target: es6`, and that merge commit was basically merging in [louy/typed-bluebird](https://github.com/louy/typed-bluebird).
