### ISSUE TITLE
Typings shouldn't have functionality tests

### ISSUE THREAD

**Issue by louy** [typed-typings/npm-bluebird#7]
I suggest getting rid of functionality tests altogether. They're not useful and they block us from having more extensive type tests. I'd rather have something like what's in [`env-node`](https://github.com/typed-typings/env-node/tree/master/4/test) and [`typed-sequelize`](https://github.com/louy/typed-sequelize/tree/master/test).

**Comment by louy** [comment]
cc @unional

**Comment by unional** [comment]
I think it is needed, as described in:
https://github.com/typings/generator-typings/issues/61#issuecomment-207539007

What do you think?

**Comment by louy** [comment]
I see your point. Agreed. this would've prevented #9.
