### ISSUE TITLE
Promise.reflect() definition

### ISSUE THREAD

**Issue by jacobdr** [typed-typings/npm-bluebird#9]
Was looking at latest definition file and didn't see that the [`.reflect`](http://bluebirdjs.com/docs/api/reflect.html) method does not appear. 

Is it possible that the [`.inspect`](https://github.com/typed-typings/npm-bluebird/blob/master/bluebird.d.ts#L132) method is a vestige from a previous version of the API?

**Comment by unional** [comment]
It is ported from DT. So you are likely to be correct. 

I'll be busy in the next three weeks so I don't have much time to work on things. Feel free to submit PR to fix it. :)

**Comment by jacobdr** [comment]
Taken care of. Will close this issue upon successful merge. For those who may have relied on `.inspect` method from v2.x.x of Bluebird ([removed](https://github.com/petkaantonov/bluebird/commit/edcd4af641c79d93901d9937cf470ffd3731f4f4#diff-71a33078d64e28db727b5848b796c751) in 2014), see comments in the PR #10

**Comment by jacobdr** [comment]
Great. PR has been submitted here
https://github.com/typed-typings/npm-bluebird/pull/10

**Comment by louy** [comment]
I think `.settle` was also deprecated, right? I can't find it anywhere in the docs.

**Comment by jacobdr** [comment]
All set to merge. I'm not sure if the API is fully up to date, but I will
continue to submit further PRs as I find issues.

**Comment by louy** [comment]
Cool. Thank you @jacobdr!

**Comment by jacobdr** [comment]
Still need to submit the PR to the typings registry, right?

**Comment by louy** [comment]
I already did. https://github.com/typings/registry/pull/357

**Comment by jacobdr** [comment]
Awesome. Sorry I didn't catch that.

JR
